# tie everything together
# the following files will NOT bundled into the final app - they are just helpers in the SDK
source("src/common/logger.R")
source("src/common/runtime_configuration.R")
source("src/io/app_files.R")
source("src/io/io_handler.R")
source("src/io/rds.R")

library("shiny")
library("tidyverse")
library("fs")

Sys.setenv(tz="UTC")

bookmarkRootDir = "shiny_bookmarks"
bookmarkDir <- paste0(bookmarkRootDir, "/latest")
bookmarkFileName <- "bookmark.rds"

ui <- function(request) { 
  fluidPage(
    tags$head(singleton(tags$script(src = 'ws-keep-alive-fix.js'))),
    tags$link(rel = "stylesheet", type = "text/css", href = "ws-keep-alive-fix.css"),
    shinyModuleUserInterface("shinyModule"),
    dataTableOutput("table"), #Is necessary for storing result

    # ws-heartbeat fix
    # kudos: https://github.com/rstudio/shiny/issues/2110#issuecomment-419971302
    textOutput("ws_heartbeat"),
    # store the current state (as a shiny bookmark)
    bookmarkButton(title="Save state",class="btn btn-outline-success")
  )
}

server <- function(input, output, session) {
  tryCatch(
  {
    data <- readInput(sourceFile())
    shinyModuleArgs <- c(shinyModule, "shinyModule")
    if (!is.null(data)) {
        shinyModuleArgs[["data"]] <- data
    }

    result <- do.call(callModule, shinyModuleArgs)

    observeEvent(
      session,
      {
        if(file_exists(path(bookmarkDir, bookmarkFileName)) && is.null(parseQueryString(session$clientData$url_search)$`_state_id_`)) {
          updateQueryString(queryString = "?_state_id_=latest")
          logger.info("Reloading session b/c of detected (not yet loaded) shiny bookmark")
          session$reload()
        }
      },
      once = TRUE
    )

    output$table <- renderDataTable({
      storeResult(result(), outputFile())
      notifyDone("SHINY")
    })
  },
  error = function(e) {
    # error handler picks up where error was generated
    print(paste("ERROR: ", e))
    storeToFile(e, errorFile())
    if (grepl("[code 10]", e$message, fixed=TRUE)) {
      stopApp(10)
    } else {
      stop(e) # re-throw the exception
    }
  })

  # ws-heartbeat fix
  # kudos: https://github.com/rstudio/shiny/issues/2110#issuecomment-419971302
  output$ws_heartbeat <- renderText({
    req(input$heartbeat)
    input$heartbeat
  })
  
  # hook after persisting the bookmark
  # see https://shiny.rstudio.com/articles/advanced-bookmarking.html
  onBookmarked(function(url) {
    stateId <- parseQueryString(sub("^.*\\?", "", url))$`_state_id_`
    if(!dir_exists(bookmarkDir)){
      dir_create(bookmarkDir)
    }
    file_move(
      path = path(bookmarkRootDir, stateId, "input.rds"), # `input.rds` is the file generated by shiny
      new_path = path(bookmarkDir, bookmarkFileName)
    )
    dir_delete(path(bookmarkRootDir, stateId))
    logger.info(paste("Moved shiny bookmark", stateId, "to", bookmarkDir))
  })
}

simulateMoveAppsRun <- function(args) {
  shinyApp(ui, server, enableBookmarking="server")
}
